---
- name: sample_job1
  hosts: all
  become: "yes"
  gather_facts: false
  tasks:

    - name: get pwd
      command: pwd
      register: pwd_result
      tags:
        - skip_ansible_lint

    - debug: var=pwd_result

    - name: Register pwd_result
      set_fact:
        pwd_fact: pwd_result.stdout

    - debug: var="{{ pwd_fact }}"

    - set_stats:
        data:
          pwd_stats: "{{ pwd_result.stdout }}"
